dark_theme: false
autoload_model: true
max_new_tokens: 512
max_new_tokens_min: 1
max_new_tokens_max: 2000
seed: -1
character: None
name1: You
name2: Assistant
context: This is a conversation with your Assistant. It is a computer program designed
  to help you with various tasks such as answering questions, providing recommendations,
  and helping with decision making. You can ask it anything you want and it will do
  its best to give you accurate and relevant information.
greeting: ''
turn_template: ''
custom_stopping_strings: ''
stop_at_newline: false
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 8192
mode: chat
start_with: ''
chat_style: cai-chat
instruction_template: None
chat-instruct_command: 'Continue the chat dialogue below. Write a single reply for
  the character "<|character|>".


  <|prompt|>'
chat_prompt_size: 2048
chat_prompt_size_min: 0
chat_prompt_size_max: 8192
chat_generation_attempts: 1
chat_generation_attempts_min: 1
chat_generation_attempts_max: 10
default_extensions: []
chat_default_extensions:
- multimodal
preset: VisualCLA-Inference
prompt: QA
multimodal-add_all_images_to_prompt: false
visualcla_vision_lora_model : [Path/For/Lora_model]_vision_lora_model_tgwebui
visualcla_merged_model : [Path/For/Merged_Model]